# HTTP server configurations
server:
  port: 8080
  readTimeout: 10
  writeTimeout: 10
  maxHeaderKilobytes: 1024

# PostgreSQL database configurations
db:
  host: pgdb
  port: 5432
  user: postgres
  name: postgres
  sslMode: disable
